server:
  port: 8082
spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:h2:mem:bookingdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

event:
  service:
    url: http://localhost:8081/api/v1/events